[server]
server_url = "https://www.mxxshop.com"
server_host = "127.0.0.1"
server_port = 8080
# 默认语言
default_lang = "en"
# saas域名
saas_domain = "abc.com"

#jwt的令牌
jwt_secret_admin = "mxx_b2b_admin56789"
jwt_secret_user = "mxx_b2b_user1234567"
#jwt过期时间,过期时间(秒)
jwt_expire_admin = 36000
#用户端jwt过期时间,过期时间(秒)，24小时=86400
jwt_expire_user = 1200
#默认模版
tpl_default = "default"
#缓存设置 choose ("mem","redis")
cache_type = "mem"
#debug模式
debug = false
#用于搜索的索引名称
index_name = "search_index"
#权限放行URL列表，多个用逗号分隔
permission_exclude_urls = "/api/system/auth/login,/api/system/auth/logout,/api/user/auth/login,/api/user/auth/logout,/api/user/wechat/login,/api/system/auth/captcha,/api/finance/payment/wechat-notify"


# 数据库
[db]
url = "postgres://postgres:123456@127.0.0.1:5432/mxxcrm_data"
max_connections = 100
min_connections = 5
connect_timeout = 8
acquire_timeout = 8
idle_timeout = 8
max_lifetime = 8
logging = false
logging_level = "info"

# redis 链接
[redis]
url = "redis://127.0.0.1:6379"

[attach]
attach_path = "./storage/Attach/"
#上传路径，需要/结尾
upload_path = "./storage/upload/"
upload_url = "/upload/"
#静态文件服务器地址，用于访问上传的静态文件
static_url = "https://static.s88.cn"

# 微信小程序配置
[wechat]
app_id = "wx2384cfda6cc622d4"
app_secret = "c55510aa5c74d827c907b65472d1d571"


# 时区配置
[time]
timezone = "Asia/Shanghai"
